# Generated by Django 5.2.8 on 2025-11-15 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('localidade', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(default='Portugal', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data', models.DateField()),
                ('localidade', models.CharField(max_length=120)),
                ('distancia_km', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
                ('dificuldade_factor', models.FloatField(default=1.0)),
                ('tempo_vencedor_segundos', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('is_manual', models.BooleanField(default=False)),
                ('bonus_type', models.CharField(default='default', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('região', models.CharField(blank=True, max_length=120)),
                ('aprovado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.club')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_segundos', models.IntegerField()),
                ('posicao_geral', models.IntegerField(blank=True, null=True)),
                ('posicao_escalao', models.IntegerField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, max_length=120)),
                ('is_official', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.athlete')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.race')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='temporada_automatica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races_automaticas', to='api.season'),
        ),
        migrations.AddField(
            model_name='race',
            name='temporadas_manuais',
            field=models.ManyToManyField(blank=True, related_name='races_manuais', to='api.season'),
        ),
    ]
